### ISSUE TITLE
Music sync from general PC sources not Spotify 

### ISSUE THREAD

**Issue by kdlilly** [winleafs/Winleafs#193]
Hi,

Not a bug as a request for help as I cannot find a way to do what I need anywhere.  All I want to do is set my canvas rhythm to use the input from the PC sound channel not from the microphone in the canvas tile.  Exactly like your Spotify but in my case from VirtualDJ.

Anyone can help I can’t tell you how grateful I would be for a solution!

Thanks all

**Comment by StijnOostdam** [comment]
Hey,

I am not quite sure what you mean. Our Spotify function simply checks which playlist is playing and if it matches with one of your chosen playlists in a schedule, Winleafs sets the chosen effect and brightness. So our Spotify function does not analyze and react to music that is being played on the computer.

I think what you want is to analyze the PC audio and then send commands to the Nanoleaf lights to set colors. The reason we do not have this is in Winleafs is because this is a difficult task that is already nicely solved by Nanoleaf themselves. It is definitely possible to build it in Winleafs (or a separate program) but to get it performing as good as the Nanoleaf effects is difficult.

**Comment by kdlilly** [comment]
Firstly thank you so much for the very fast response.

What I was trying to say is using the audio channel on the pc whatever
application is playing through the midi channel to drive the canvas as
there is no option for a physical line in on the canvas and using the built
in Mic gives inconsistent results.

Thanks that is what I’m trying to solve, hopefully better explained this
time?

Kurt

**Comment by StijnOostdam** [comment]
So I think what I described, describes what you want:

> I think what you want is to analyze the PC audio and then send commands to the Nanoleaf lights to set colors. The reason we do not have this is in Winleafs is because this is a difficult task that is already nicely solved by Nanoleaf themselves. It is definitely possible to build it in Winleafs (or a separate program) but to get it performing as good as the Nanoleaf effects is difficult.

What I mean is that we would make a custom effect that reacts to music played by a PC, instead of reacting to a mic.

As I said however, this is a difficult problem and since Nanoleafs already has it built in (be it only via mic), we are currently not planning on developing this feature.

**Comment by kdlilly** [comment]
Yes, it does, I was just hoping there was a way to use all Nanoleaf’s work
and just send the audio channel instead of using the inbuilt mic.

I guess the alternative is to pull apart a control square and replace mic
with line in.

Thanks for all your help and insight, I truly appreciate the time you’ve
taken to respond.

**Comment by StijnOostdam** [comment]
Glad to hear, happy to help and let us know if there is anywhing else
